import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, ArrowsClockwise, CaretLeft, CaretRight, CheckCircle, CircleNotch, ClockCounterClockwise, DownloadSimple, Receipt, Key, LockKey, MagnifyingGlass, PencilSimple, Plus, ShieldCheck, SignOut, Ticket, User, Users } from '@phosphor-icons/react';
import { z } from 'zod';
import { sessionChanged } from '../session';
import { AdminError, adminCall, auditSchema, date, errorMessage, inviteSchema, inviteStatus, memberSchema, memberStatus, number, statusLabels, type Audit, type Identity, type Invite, type Member } from './api';
import { Credential, EditorDialog, InviteEditor, UserEditor } from './AdminEditors';
import './admin.css';
import { BillingPanel } from '../components/BillingPanel';

type View='users'|'invites'|'audit'|'billing';
const viewOfPath=():View=>window.location.pathname.startsWith('/admin/billing')?'billing':window.location.pathname.startsWith('/admin/invites')?'invites':window.location.pathname.startsWith('/admin/audit')?'audit':'users';
const titles:Record<View,string>={users:'用户管理',invites:'邀请码',audit:'操作记录',billing:'费用账单'};

function AdminLogin({onLogin,initialError}:{onLogin:(user:Identity)=>void;initialError:string}){
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(initialError);
  async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const value=await adminCall('/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(z.object({id:z.string(),email:z.string(),isAdmin:z.literal(true)}).parse(value.user));sessionChanged();}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}
  return <main className="admin-login"><a className="admin-brand" href="/"><img src="/brand/yingya-ghost.png" alt=""/><span>映芽</span></a><section><div className="admin-login-symbol"><ShieldCheck/></div><h1>管理后台</h1><p>登录你的管理员账号</p><form onSubmit={event=>void submit(event)}><label>邮箱<div className="admin-login-input"><User/><input name="email" type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} maxLength={254} required disabled={busy}/></div></label><label>密码<div className="admin-login-input"><LockKey/><input name="password" type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} maxLength={128} required disabled={busy}/></div></label>{error?<p className="admin-error" role="alert">{error}</p>:null}<button className="admin-button primary" disabled={busy}>{busy?<CircleNotch className="spin"/>:<ArrowRight/>}{busy?'正在登录…':'登录管理后台'}</button></form><a className="admin-return" href="/app"><ArrowLeft/>返回创作工作台</a></section><footer>映芽 · 管理后台</footer></main>;
}

function StateTag({status}:{status:string}){return <span className={`admin-state ${status==='active'?'active':''}`}><span aria-hidden="true"/>{statusLabels[status]||status}</span>;}
function auditDescription(record:Audit){
  try{const details=JSON.parse(record.details);const labels:Record<string,string>={email:'邮箱',username:'用户名',name:'姓名',isAdmin:'管理员',status:'状态',tokenLimit:'Token 总额度',mediaLimit:'素材次数',maxUses:'可用次数',expiresAt:'到期时间',revoked:'停用邀请',label:'邀请名称'};
    const value=(key:string,item:unknown)=>key==='expiresAt'?date(Number(item)):typeof item==='boolean'?(item?'是':'否'):typeof item==='number'?number(item):key==='status'?(statusLabels[String(item)]||String(item)):String(item??'未设置');
    return Object.entries(details.after||details).filter(([key,item])=>key in labels&&(!details.before||details.before[key]!==item)).map(([key,item])=>`${labels[key]}：${details.before?`${value(key,details.before[key])} → `:''}${value(key,item)}`).join('；')||record.action;
  }catch{return record.action;}
}

export function AdminApp(){
  const [identity,setIdentity]=useState<Identity|null>(null),[restoring,setRestoring]=useState(true),[error,setError]=useState('');
  const [view,setView]=useState<View>(viewOfPath),[members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invite[]>([]),[audit,setAudit]=useState<Audit[]>([]);
  const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[notice,setNotice]=useState('');
  const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(1);
  const [security,setSecurity]=useState(false);
  const [userEditor,setUserEditor]=useState<Member|null|undefined>(undefined),[inviteEditor,setInviteEditor]=useState<Invite|null|undefined>(undefined),[credential,setCredential]=useState<{label:string;url:string}|null>(null),[confirmation,setConfirmation]=useState<Member|null>(null);
  function handleError(error:unknown){setError(errorMessage(error));if(error instanceof AdminError&&(error.status===401||error.status===403)){setIdentity(null);setUserEditor(undefined);setInviteEditor(undefined);setCredential(null);setConfirmation(null);setSecurity(false);}}
  useEffect(()=>{let active=true;void adminCall('/me').then(value=>{if(active)setIdentity(value.user);}).catch(error=>{if(active&&!(error instanceof AdminError&&[401,403].includes(error.status)))setError(errorMessage(error));}).finally(()=>{if(active)setRestoring(false);});return()=>{active=false;};},[]);
  useEffect(()=>{const sync=()=>{setView(viewOfPath());setSearch('');setFilter('all');setPage(1);};const session=(event:StorageEvent)=>{if(event.key==='yingya-session-change')window.location.reload();};window.addEventListener('popstate',sync);window.addEventListener('storage',session);return()=>{window.removeEventListener('popstate',sync);window.removeEventListener('storage',session);};},[]);
  useEffect(()=>{if(!identity)return;const controller=new AbortController();setLoading(true);void Promise.all([adminCall('/accounts',{signal:controller.signal}),adminCall('/invites',{signal:controller.signal}),adminCall('/audit',{signal:controller.signal})]).then(([users,codes,records])=>{setMembers(z.array(memberSchema).parse(users.users));setInvites(z.array(inviteSchema).parse(codes.invites));setAudit(z.array(auditSchema).parse(records.records));}).catch(error=>{if(!controller.signal.aborted)handleError(error);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[identity,refresh]);
  function navigate(next:View){window.history.pushState(null,'',`/admin/${next}`);setView(next);setSearch('');setFilter('all');setPage(1);setError('');setNotice('');}
  async function mutation(work:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await work();setRefresh(value=>value+1);}catch(error){handleError(error);}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{const response=await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!response.ok)throw new Error('退出失败，请重试');sessionChanged();setIdentity(null);setMembers([]);setInvites([]);setAudit([]);setError('');}catch(error){handleError(error);}finally{setBusy(false);}}
  async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);if(data.get('new')!==data.get('confirm')){setError('两次输入的密码不一致');return;}await mutation(async()=>{await adminCall('/password',{method:'POST',body:JSON.stringify({currentPassword:data.get('current'),newPassword:data.get('new')})});setSecurity(false);setIdentity(null);setNotice('');setError('密码已修改，请重新登录');sessionChanged();});}
  async function saveUser(input:Record<string,unknown>){await mutation(async()=>{if(userEditor){await adminCall(`/accounts/${userEditor.id}/profile`,{method:'PATCH',body:JSON.stringify(input)});}else{await adminCall('/accounts',{method:'POST',body:JSON.stringify(input)});}setUserEditor(undefined);setNotice(userEditor?'用户资料已保存':'用户已创建');});}
  async function saveInvite(input:Record<string,unknown>){await mutation(async()=>{if(inviteEditor){await adminCall(`/invites/${inviteEditor.id}`,{method:'PATCH',body:JSON.stringify(input)});setNotice('邀请已更新，新额度用于之后的兑换');}else{const result=await adminCall('/invites',{method:'POST',body:JSON.stringify(input)});setCredential({label:'邀请链接',url:`${window.location.origin}/app#${new URLSearchParams({invite:result.code,...(input.email?{email:String(input.email)}:{})})}`});setNotice('邀请码已生成');}setInviteEditor(undefined);});}
  async function userAction(action:'reset'|'sessions',member:Member){let link:string|undefined;if(action==='sessions'){setConfirmation(member);return;}await mutation(async()=>{const result=await adminCall('/password-reset',{method:'POST',body:JSON.stringify({email:member.email})});link=`${window.location.origin}/app#${new URLSearchParams({reset:result.code,email:member.email})}`;setNotice('密码重置链接已生成');});return link;}
  const needle=search.trim().toLowerCase();
  const filteredMembers=members.filter(member=>(filter==='all'||(filter==='admin'?member.isAdmin:memberStatus(member)===filter))&&[member.email,member.username,member.name,member.notes].some(value=>value?.toLowerCase().includes(needle)));
  const filteredInvites=invites.filter(invite=>(filter==='all'||inviteStatus(invite)===filter)&&[invite.email,invite.label,invite.id].some(value=>value?.toLowerCase().includes(needle)));
  const filteredAudit=audit.filter(record=>(filter==='all'||record.action===filter)&&[record.actor,record.action,record.targetName,auditDescription(record)].some(value=>value.toLowerCase().includes(needle)));
  const total=view==='users'?filteredMembers.length:view==='invites'?filteredInvites.length:filteredAudit.length;
  const pages=Math.max(1,Math.ceil(total/20)),currentPage=Math.min(page,pages),start=(currentPage-1)*20;
  function exportUsers(){const rows=[['姓名','用户名','邮箱','角色','状态','Token 总额度','已用 Token','剩余 Token','素材总次数','已用素材次数'],...filteredMembers.map(member=>[member.name,member.username||'',member.email,member.isAdmin?'管理员':'用户',statusLabels[memberStatus(member)],member.quota.tokenLimit,member.quota.usedTokens,member.quota.remainingTokens,member.quota.mediaLimit,member.quota.usedMedia])];const csv=rows.map(row=>row.map(value=>{let text=String(value);if(/^[=+\-@\t\r]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`;}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff',csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='yingya-users.csv';anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
  if(restoring)return <main className="state-screen" role="status"><CircleNotch className="spin"/>正在打开管理后台…</main>;
  if(!identity)return <AdminLogin initialError={error} onLogin={user=>{setIdentity(user);setError('');}}/>;
  return <div className="admin-shell"><aside className="admin-sidebar"><a href="/admin/users" className="admin-brand" onClick={event=>{if(!event.metaKey&&!event.ctrlKey){event.preventDefault();navigate('users');}}}><img src="/brand/yingya-ghost.png" alt=""/><span>映芽<small>管理后台</small></span></a><nav aria-label="后台导航">{([['users',Users],['invites',Ticket],['billing',Receipt],['audit',ClockCounterClockwise]] as const).map(([key,Icon])=><a key={key} href={`/admin/${key}`} aria-current={view===key?'page':undefined} onClick={event=>{if(!event.metaKey&&!event.ctrlKey){event.preventDefault();navigate(key);}}}><Icon/>{titles[key]}</a>)}</nav><div className="admin-sidebar-bottom"><a href="/app"><ArrowLeft/>创作工作台</a><span title={identity.email}><ShieldCheck/>{identity.email}</span><button className="admin-security-button" disabled={busy} onClick={()=>{setError('');setSecurity(true);}}><Key/>修改密码</button><button disabled={busy} onClick={()=>void logout()}><SignOut/>退出登录</button></div></aside>
    <main className="admin-main">{view==='billing'?<BillingPanel administrative members={members} onAuthenticationError={()=>handleError(new AdminError('登录已失效，请重新登录',401))}/>:<><header className="admin-page-heading"><div><p>映芽 / 管理后台</p><h1>{titles[view]}</h1></div><div className="admin-toolbar-actions"><button className="admin-icon" title="刷新" aria-label="刷新" disabled={loading||busy} onClick={()=>setRefresh(value=>value+1)}><ArrowsClockwise className={loading?'spin':''}/></button>{view==='users'?<><button className="admin-button" onClick={exportUsers} disabled={loading}><DownloadSimple/>导出</button><button className="admin-button primary" onClick={()=>{setError('');setUserEditor(null);}}><Plus/>创建用户</button></>:view==='invites'?<button className="admin-button primary" onClick={()=>{setError('');setInviteEditor(null);}}><Plus/>创建邀请码</button>:null}</div></header>
      <section className="admin-summary" aria-label="后台汇总">{(view==='users'?[['全部用户',members.length],['已启用',members.filter(member=>memberStatus(member)==='active').length],['待激活',members.filter(member=>memberStatus(member)==='pending').length],['累计 Token',members.reduce((sum,member)=>sum+member.quota.usedTokens,0)]]:view==='invites'?[['邀请总数',invites.length],['有效邀请',invites.filter(invite=>inviteStatus(invite)==='active').length],['累计兑换',invites.reduce((sum,invite)=>sum+invite.uses,0)],['已停用',invites.filter(invite=>invite.revoked).length]]:[['近期操作',audit.length],['操作管理员',new Set(audit.map(record=>record.actor)).size]]).map(([label,value])=><div key={label}><span>{label}</span><strong>{number(Number(value))}</strong></div>)}</section>
      {notice?<p className="admin-notice" role="status"><CheckCircle/>{notice}</p>:null}{error&&userEditor===undefined&&inviteEditor===undefined?<p className="admin-error" role="alert">{error}</p>:null}
      <div className="admin-filters"><div className="admin-search"><MagnifyingGlass/><input aria-label="搜索" placeholder={view==='users'?'搜索姓名、用户名或邮箱':view==='invites'?'搜索邀请名称或邮箱':'搜索操作人或内容'} value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}}/></div><select aria-label="筛选状态" value={filter} onChange={event=>{setFilter(event.target.value);setPage(1);}}><option value="all">{view==='audit'?'全部操作':'全部状态'}</option>{(view==='users'?['active','pending','disabled','archived','admin']:view==='invites'?['active','spent','expired','revoked']:Array.from(new Set(audit.map(record=>record.action)))).map(value=><option key={value} value={value}>{value==='admin'?'管理员':statusLabels[value]||value}</option>)}</select><span>{total} 条记录</span></div>
      <div className="admin-table-scroll" tabIndex={0} aria-label={titles[view]} aria-busy={loading}>
        {view==='users'?<table><thead><tr><th>用户</th><th>角色</th><th>状态</th><th>Token 用量 / 总额</th><th>素材次数</th><th>最近登录</th><th>操作</th></tr></thead><tbody>{filteredMembers.slice(start,start+20).map(member=><tr key={member.id}><th scope="row"><span className="admin-user-name">{member.name||member.username||member.email}</span><small>{member.email}</small>{member.username&&member.name?<small>@{member.username}</small>:null}</th><td>{member.isAdmin?<span className="admin-role"><ShieldCheck/>管理员</span>:'普通用户'}</td><td><StateTag status={memberStatus(member)}/></td><td><span>{number(member.quota.usedTokens)} <span className="admin-muted">/ {number(member.quota.tokenLimit)}</span></span><small>剩余 {number(member.quota.remainingTokens)}</small></td><td>{number(member.quota.usedMedia)} / {number(member.quota.mediaLimit)}</td><td>{date(member.lastLogin)}</td><td><button className="admin-icon" title={`管理 ${member.email}`} aria-label={`管理 ${member.email}`} onClick={()=>{setError('');setUserEditor(member);}}><PencilSimple/></button></td></tr>)}</tbody></table>:view==='invites'?<table><thead><tr><th>邀请</th><th>状态</th><th>兑换次数</th><th>每人 Token 额度</th><th>素材次数</th><th>到期时间</th><th>操作</th></tr></thead><tbody>{filteredInvites.slice(start,start+20).map(invite=><tr key={invite.id}><th scope="row"><span className="admin-user-name">{invite.label||invite.email||'通用邀请'}</span><small>{invite.label?(invite.email||'任意新邮箱'):invite.id.slice(0,8)}{invite.admin?' · 管理员邀请':''}</small></th><td><StateTag status={inviteStatus(invite)}/></td><td>{invite.uses} / {invite.maxUses}</td><td>{number(invite.tokenLimit)}</td><td>{number(invite.mediaLimit)}</td><td>{date(invite.expiresAt)}</td><td><button className="admin-icon" title="编辑邀请" aria-label={`编辑邀请 ${invite.label||invite.email||invite.id}`} onClick={()=>{setError('');setInviteEditor(invite);}}><PencilSimple/></button></td></tr>)}</tbody></table>:<table><thead><tr><th>时间</th><th>操作人</th><th>操作</th><th>对象</th><th>变更内容</th></tr></thead><tbody>{filteredAudit.slice(start,start+20).map(record=><tr key={record.id}><td>{date(record.createdAt)}</td><td>{record.actor}</td><td>{record.action}</td><td>{record.targetName}</td><td className="admin-audit-details">{auditDescription(record)}</td></tr>)}</tbody></table>}
        {!total?<div className="admin-empty">{loading?<><CircleNotch className="spin"/>正在读取数据…</>:<><MagnifyingGlass/><p>{search||filter!=='all'?'没有符合条件的记录':'暂无记录'}</p></>}</div>:null}
      </div><footer className="admin-pagination"><span>{total?`${start+1}–${Math.min(start+20,total)} / ${total}`:'0 条记录'}{view==='audit'?' · 最近 500 条操作':''}</span><div><button className="admin-icon" aria-label="上一页" title="上一页" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}><CaretLeft/></button><span>{currentPage} / {pages}</span><button className="admin-icon" aria-label="下一页" title="下一页" disabled={currentPage>=pages} onClick={()=>setPage(currentPage+1)}><CaretRight/></button></div></footer>
    </>}</main>
    {userEditor!==undefined?<UserEditor key={userEditor?.id||'new'} member={userEditor} currentId={identity.id} busy={busy} onClose={()=>{setUserEditor(undefined);setError('');}} onSave={saveUser} onAction={userAction} error={error}/>:null}
    {inviteEditor!==undefined?<InviteEditor key={inviteEditor?.id||'new'} invite={inviteEditor} busy={busy} onClose={()=>{setInviteEditor(undefined);setError('');}} onSave={saveInvite} error={error}/>:null}
    {credential?<EditorDialog title="邀请码已生成" busy={false} onClose={()=>setCredential(null)}><div className="admin-dialog-body"><Credential label={credential.label} url={credential.url}/><p className="admin-help">此链接只显示一次，请保存后发送给受邀用户。</p><footer><button className="admin-button primary" onClick={()=>setCredential(null)}><CheckCircle/>完成</button></footer></div></EditorDialog>:null}
    {security?<EditorDialog title="修改密码" busy={busy} onClose={()=>{setSecurity(false);setError('');}}><form onSubmit={event=>void changePassword(event)}><div className="admin-fields"><label className="admin-wide">当前密码<input name="current" type="password" autoComplete="current-password" required maxLength={128}/></label><label className="admin-wide">新密码<input name="new" type="password" autoComplete="new-password" required minLength={10} maxLength={128}/></label><label className="admin-wide">确认新密码<input name="confirm" type="password" autoComplete="new-password" required minLength={10} maxLength={128}/></label></div>{error?<p className="admin-error" role="alert">{error}</p>:null}<footer><button className="admin-button primary" disabled={busy}><CheckCircle/>保存密码</button></footer></form></EditorDialog>:null}
    {confirmation?<EditorDialog title="撤销登录会话" busy={busy} onClose={()=>setConfirmation(null)}><div className="admin-dialog-body"><p>将退出 {confirmation.email} 的所有已登录设备。</p><footer><button className="admin-button" disabled={busy} onClick={()=>setConfirmation(null)}>取消</button><button className="admin-button primary" disabled={busy} onClick={()=>void mutation(async()=>{await adminCall(`/accounts/${confirmation.id}/sessions`,{method:'DELETE'});setConfirmation(null);setNotice('该用户的登录会话已撤销');if(confirmation.id===identity.id){setUserEditor(undefined);setIdentity(null);sessionChanged();}})}><SignOut/>确认撤销</button></footer></div></EditorDialog>:null}
  </div>;
}
