import { chromium, request } from 'playwright';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync } from 'node:fs';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
const repo=fileURLToPath(new URL('..',import.meta.url)),session='yingya-admin-qa',base='http://127.0.0.1:8800';
const existing = await fetch(`${base}/health`).catch(() => null);
assert.equal(existing, null, 'Port 8800 must be free for isolated admin QA');
const root=mkdtempSync('/tmp/yingya-admin-qa-');
const env={...process.env,YINGYA_APP_DATA_DIR:root,YINGYA_ADDR:'127.0.0.1:8800',YINGYA_SECURE_COOKIES:'false',YINGYA_ADMIN_EMAILS:'admin@example.test'};
const owner=JSON.parse(execFileSync(`${repo}/target/debug/yingya-server`,['admin-create','admin','admin@example.test'],{cwd:repo,env,encoding:'utf8'}));
assert.notEqual(spawnSync('tmux',['has-session','-t',`=${session}`]).status,0);
execFileSync('tmux',['new-session','-d','-s',session,'-c',repo,...Object.entries(env).filter(([key])=>!['TMUX','TMUX_PANE'].includes(key)).flatMap(([key,value])=>['-e',`${key}=${value}`]),`${repo}/target/debug/yingya-server`]);
let browser;const errors=[];
async function shot(page,name){await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('vite-error-overlay').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${name}: page overflow`);await page.screenshot({path:`/tmp/yingya-admin-${name}.png`,fullPage:false});}
async function body(response){assert.ok(response.ok(),`${response.status()}: ${await response.text()}`);return response.json();}
try{
  for(let i=0;i<100;i++){try{if((await fetch(`${base}/health`)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:960}});const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('console',msg=>{if(msg.type()==='error'&&!msg.text().includes('Failed to load resource'))errors.push(msg.text());});
  await page.goto(`${base}/admin`);await page.getByLabel('邮箱',{exact:true}).waitFor();await shot(page,'login-desktop');
  await page.getByLabel('邮箱',{exact:true}).fill(owner.email);await page.getByLabel('密码',{exact:true}).fill('wrong-password');await page.getByRole('button',{name:'登录管理后台'}).click();await page.getByRole('alert').waitFor();
  await page.getByLabel('密码',{exact:true}).fill(owner.password);await page.getByRole('button',{name:'登录管理后台'}).click();await page.getByRole('heading',{name:'用户管理',exact:true}).waitFor();
  await page.getByRole('button',{name:'创建用户',exact:true}).click();let dialog=page.getByRole('dialog');assert.equal(await dialog.getByLabel('Token 总额度',{exact:true}).inputValue(),'1000000000');assert.equal(await dialog.getByLabel('素材生成总次数',{exact:true}).inputValue(),'40');await dialog.getByLabel('姓名',{exact:true}).fill('林小满');await dialog.getByLabel('用户名',{exact:true}).fill('linxiaoman');await dialog.getByLabel('邮箱',{exact:true}).fill('lin@example.test');await dialog.getByLabel('初始密码',{exact:true}).fill('member-strong-password');await dialog.getByRole('button',{name:'创建用户',exact:true}).click();await page.getByText('用户已创建',{exact:true}).waitFor();
  assert.equal((await body(await context.request.get(`${base}/api/admin/accounts`))).users.find(user=>user.email==='lin@example.test').quota.tokenLimit,1000000000);await page.getByLabel('搜索',{exact:true}).fill('林小满');await page.getByRole('button',{name:'管理 lin@example.test',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('管理员备注',{exact:true}).fill('第一批内测，视频制作');await dialog.getByLabel('Token 总额度',{exact:true}).fill('2000000');await dialog.getByLabel('素材生成总次数',{exact:true}).fill('40');await shot(page,'user-editor');await dialog.getByRole('button',{name:'保存更改'}).click();await page.getByText('用户资料已保存',{exact:true}).waitFor();
  const members=await body(await context.request.get(`${base}/api/admin/accounts`));let member=members.users.find(user=>user.email==='lin@example.test');assert.equal(member.quota.tokenLimit,2000000);assert.equal(member.notes,'第一批内测，视频制作');
  await page.getByLabel('搜索',{exact:true}).fill('');assert.match(await page.locator('tbody').innerText(),/1B/);assert.match(await page.locator('tbody').innerText(),/2M/);await shot(page,'users-desktop');
  const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'导出',exact:true}).click()]);assert.equal(download.suggestedFilename(),'yingya-users.csv');const csv=await download.createReadStream();let csvText='';for await(const chunk of csv)csvText+=chunk.toString();assert.match(csvText,/"1000000000"/);assert.match(csvText,/"2000000"/);
  await page.getByRole('link',{name:'邀请码',exact:true}).click();await page.getByRole('button',{name:'创建邀请码',exact:true}).click();dialog=page.getByRole('dialog');assert.equal(await dialog.getByLabel('每人 Token 额度',{exact:true}).inputValue(),'1000000000');assert.equal(await dialog.getByLabel('每人素材生成次数',{exact:true}).inputValue(),'40');await dialog.getByLabel('可使用次数',{exact:true}).fill('3');await dialog.getByLabel('每人 Token 额度',{exact:true}).fill('1000');await dialog.getByRole('button',{name:'生成邀请码',exact:true}).click();await page.getByRole('heading',{name:'邀请码已生成'}).waitFor();const link=await page.getByRole('dialog').getByLabel('邀请链接').inputValue();const code=new URLSearchParams(new URL(link).hash.slice(1)).get('invite');await page.getByRole('button',{name:'完成',exact:true}).click();
  const first=await request.newContext();let firstUser=await body(await first.post(`${base}/api/auth/register`,{data:{email:'first@example.test',password:'first-test-password',invite_code:code}}));
  await page.getByRole('button',{name:'刷新',exact:true}).click();await page.getByRole('button',{name:/编辑邀请/}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('邀请名称',{exact:true}).fill('创作者内测');await dialog.getByLabel('每人 Token 额度',{exact:true}).fill('5000');await dialog.getByLabel('每人素材生成次数',{exact:true}).fill('30');await shot(page,'invite-editor-desktop');await dialog.getByRole('button',{name:'保存邀请',exact:true}).click();await page.getByText('邀请已更新，新额度用于之后的兑换',{exact:true}).waitFor();
  const second=await request.newContext();await body(await second.post(`${base}/api/auth/register`,{data:{email:'second@example.test',password:'second-test-password',invite_code:code}}));assert.equal((await body(await first.get(`${base}/api/quota`))).tokenLimit,1000);assert.equal((await body(await second.get(`${base}/api/quota`))).tokenLimit,5000);
  assert.equal((await second.get(`${base}/api/admin/accounts`)).status(),403);const invitation=(await body(await context.request.get(`${base}/api/admin/invites`))).invites[0];assert.equal((await second.patch(`${base}/api/admin/invites/${invitation.id}`,{data:{revision:invitation.revision,label:invitation.label,email:invitation.email,expiresAt:invitation.expiresAt,maxUses:invitation.maxUses,tokenLimit:999999,mediaLimit:invitation.mediaLimit,revoked:false}})).status(),403);
  await page.getByRole('button',{name:'刷新',exact:true}).click();await shot(page,'invites-desktop');
  await page.setViewportSize({width:390,height:844});await shot(page,'invites-mobile');await page.getByRole('button',{name:/编辑邀请/}).click();await shot(page,'invite-editor-mobile');await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();
  await page.setViewportSize({width:320,height:740});await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('link',{name:'用户管理',exact:true}).click();await page.getByRole('button',{name:'管理 lin@example.test',exact:true}).click();await shot(page,'user-editor-320');await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();await page.evaluate(()=>{window.scrollTo(0,0);document.querySelector('.admin-main').scrollTo(0,0);document.querySelector('.admin-table-scroll').scrollTo(0,0);});await shot(page,'users-320');
  await page.setViewportSize({width:1440,height:960});await page.getByRole('button',{name:'管理 lin@example.test',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('账号状态').selectOption('archived');await dialog.getByRole('button',{name:'保存更改'}).click();await page.getByText('用户资料已保存',{exact:true}).waitFor();
  const ordinary=await request.newContext();assert.equal((await ordinary.post(`${base}/api/auth/login`,{data:{email:'lin@example.test',password:'member-strong-password'}})).status(),400);
  await page.getByLabel('筛选状态').selectOption('archived');await page.getByRole('button',{name:'管理 lin@example.test',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('账号状态').selectOption('active');await dialog.getByRole('button',{name:'保存更改'}).click();await page.getByText('用户资料已保存',{exact:true}).waitFor();await body(await ordinary.post(`${base}/api/auth/login`,{data:{email:'lin@example.test',password:'member-strong-password'}}));
  await page.getByLabel('筛选状态').selectOption('all');await page.getByRole('button',{name:'管理 lin@example.test',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'撤销登录会话',exact:true}).click();await page.getByRole('button',{name:'确认撤销'}).click();await page.getByText('该用户的登录会话已撤销',{exact:true}).waitFor();assert.equal((await ordinary.get(`${base}/api/auth/me`)).status(),401);await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();
  await page.getByRole('link',{name:'操作记录',exact:true}).click();await shot(page,'audit-desktop');await page.reload();await page.getByRole('heading',{name:'操作记录',exact:true}).waitFor();
  assert.ok((await body(await context.request.get(`${base}/api/admin/audit`))).records.length>=6);
  await page.getByRole('button',{name:'修改密码',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('当前密码',{exact:true}).fill(owner.password);await dialog.getByLabel('新密码',{exact:true}).fill('changed-admin-password');await dialog.getByLabel('确认新密码',{exact:true}).fill('changed-admin-password');await dialog.getByRole('button',{name:'保存密码'}).click();await page.getByRole('heading',{name:'管理后台',exact:true}).waitFor();await page.getByLabel('邮箱',{exact:true}).fill(owner.email);await page.getByLabel('密码',{exact:true}).fill('changed-admin-password');await page.getByRole('button',{name:'登录管理后台'}).click();await page.getByRole('heading',{name:'操作记录',exact:true}).waitFor();
  assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,root,viewports:['1440x960','390x844','320x740 reduced motion'],checks:['email/password','1B/40 defaults','compact K/M/B with exact CSV','create user','profile/quota edits','CSV export','invite edits future-only','authorization','archive/restore','session revocation','audit','own password change','route reload'],errors}));await first.dispose();await second.dispose();await ordinary.dispose();
}finally{if(browser)await browser.close();console.log(execFileSync('tmux',['capture-pane','-pt',session,'-S','-12'],{encoding:'utf8'}));execFileSync('tmux',['kill-session','-t',`=${session}`]);}
